In [1]:
from cartan_subalgebra import *
from basic import *
from general_linear import *

In [4]:
basis = np.stack([E_unit(3, 0, 0) - E_unit(3, 1, 1), E_unit(3, 1, 1) - E_unit(3, 2, 2), 
                      E_unit(3, 0, 1), E_unit(3, 0, 2), E_unit(3, 1, 2), E_unit(3, 1, 0),
                      E_unit(3, 2, 0), E_unit(3, 2, 1)])
GL = GeneralLinear(basis=basis)
print(GL.structure_constant)

[[[ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  2.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0. -1.  0.  0.  0.]
  [ 0.  0.  0.  0.  0. -2.  0.  0.]
  [ 0.  0.  0.  0.  0.  0. -1.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  1.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0. -1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  2.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  0.  0. -1.  0.]
  [ 0.  0.  0.  0.  0.  0.  0. -2.]]

 [[ 0.  0. -2.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.  0.  0.]
  [ 1.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0. -1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0. -1.  0.  0.  0.  0.]
  [ 0.  0.  0. -1.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.

In [9]:
structure_constant = GL._structure_constant()
L = LieAlgebra(structure_constant=structure_constant)
K = SubLieAlgebra(L, L.basis[:3])

In [18]:
print(f"the product between {0}-th basis and {1}-th basis given by Killing form is {Killing_form(L, x=L.basis[0], y=L.basis[1])}")
print(f"the adjoint repn of {2}-th basis is \n {adjoint(L,x=L.basis[2])}")
print(f"checking ad-nilpotency: {is_ad_nilpotent(L, x=L.basis[2] + L.basis[3] + L.basis[4])}")
print(f"checking semi-simplicity: {is_semisimple(L)}")

the product between 0-th basis and 1-th basis given by Killing form is -6.0
the adjoint repn of 2-th basis is 
 [[ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [-2.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]]
checking ad-nilpotency: True
checking semi-simplicity: True


In [21]:
CSA = cartan_subalgebra(L)
print(f"basis of CSA:\n {CSA.basis}")

basis of CSA:
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]
